/*
Create empty raw tables for the preserved FJC appellate CSV snapshots.

All columns remain text so that the imported source values are preserved.
Run tools/import_fjc_appellate_raw.sh rather than invoking this file directly
when the two tables should also be populated.
*/

\set ON_ERROR_STOP on

BEGIN;

CREATE SCHEMA IF NOT EXISTS ext;

DROP TABLE IF EXISTS ext.fjc_appellate_raw_1971to2007;
CREATE TABLE ext.fjc_appellate_raw_1971to2007 (
    circuit text,
    docket text,
    reopen text,
    dktdate text,
    usapt text,
    appellan text,
    usape text,
    appellee text,
    apptype text,
    orgproc text,
    ifp text,
    divoff text,
    agency text,
    juris text,
    nos text,
    offense text,
    othtype text,
    dcirc text,
    ddist text,
    doffice text,
    ddocket text,
    ddktdate text,
    appdate text,
    aofilemo text,
    aofileyr text,
    disp text,
    outcome text,
    procterm text,
    method text,
    pubstat text,
    opdisp text,
    joinapp text,
    consdkt text,
    crecdate text,
    brfiled text,
    subdate text,
    heardate text,
    judgdate text,
    opinion text,
    jdgcode1 text,
    jdgcode2 text,
    jdgcode3 text,
    tapeyear text,
    prosefle text,
    prosetrm text,
    statuscd text,
    trusedmo text,
    trusedyr text,
    termdate text,
    cpc text,
    cpcdisc text,
    jdgpanel text,
    cnslapp text,
    cnslcont text,
    cnsldis text,
    cnslcir text,
    newsytrm text
);

DROP TABLE IF EXISTS ext.fjc_appellate_raw_2008plus;
CREATE TABLE ext.fjc_appellate_raw_2008plus (
    circuit text,
    docket text,
    reopen text,
    dktdate text,
    usapt text,
    appellan text,
    usape text,
    appellee text,
    apptype text,
    orgproc text,
    agency text,
    juris text,
    nos text,
    offense text,
    dcirc text,
    ddist text,
    doffice text,
    ddocket text,
    ddefnum text,
    fedcap text,
    ddktdate text,
    appdate text,
    transdate text,
    transcode text,
    djudge text,
    filefee text,
    disp text,
    outcome text,
    procterm text,
    method text,
    pubstat text,
    opdisp text,
    joinapp text,
    consdkt text,
    crecdate text,
    brfiled text,
    subdate text,
    heardate text,
    judgdate text,
    opinion text,
    jdgcode1 text,
    jdg1inv text,
    jdgcode2 text,
    jdg2inv text,
    jdgcode3 text,
    jdg3inv text,
    tapeyear text,
    prosefle text,
    prosetrm text,
    statuscd text,
    enbanc text,
    trmtype text,
    torprocsub text,
    trmfee text
);

COMMIT;
